Bug 100420 - Safari Script error: undefined is not a function (evaluating 'query.startsWith ("(")')
[Problem Description]
The script error occurs when I access to the web client via Safari.  It was caused by the fix of Bug 72420.  It happens only when the zimbraFeatureContactsDetailedSearchEnabled is set to TRUE.

[Root Cause]
String.startsWith() function is not defined for Safari, Opera, and IE. 

[Fix Description]
Replace startsWith() by lastIndexOf().

[Affected Area]
Ajax Web client: Contact picker

[Configuration Changes]
None

[LDAP Schema Changes]
None

[API Changes]
None

[Log Changes]
None

[Manual Test]
Same as 72420.

https://bugzilla.zimbra.com/show_bug.cgi?id=100420

Copied from Perforce
 Change: 551512