Integrate change 535260 from JUDASPRIEST to main
-------------
Bug: 97396 - Script Error: AjxUtil.filter is not a function error is seen when any criteria is being specified in Search filter
- check in missing AjxUtil.filter function
- add missing 'var'

https://bugzilla.zimbra.com/show_bug.cgi?id=97396

Copied from Perforce
 Change: 535264